/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.bysj.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 05-13-2012
 * 
 * XDoclet definition:
 * @struts.form name="appraisalForm"
 */
public class AppraisalForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** beginTime property */
	private String beginTime;

	/** abeginTime property */
	private String abeginTime;

	/** type property */
	private String type;

	/** title property */
	private String title;

	/** aendTime property */
	private String aendTime;

	/** canping property */
	private String canping;

	/** context property */
	private String context;

	/** beiping property */
	private String[] beiping;

	/** allowAffix property */
	private Boolean allowAffix;

	/** endTime property */
	private String endTime;
	
	private String[] options;
	private int[] escores;
	private int[] tscores;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the beginTime.
	 * @return String
	 */
	public String getBeginTime() {
		return beginTime;
	}

	/** 
	 * Set the beginTime.
	 * @param beginTime The beginTime to set
	 */
	public void setBeginTime(String beginTime) {
		this.beginTime = beginTime;
	}

	/** 
	 * Returns the abeginTime.
	 * @return String
	 */
	public String getAbeginTime() {
		return abeginTime;
	}

	/** 
	 * Set the abeginTime.
	 * @param abeginTime The abeginTime to set
	 */
	public void setAbeginTime(String abeginTime) {
		this.abeginTime = abeginTime;
	}

	/** 
	 * Returns the type.
	 * @return String
	 */
	public String getType() {
		return type;
	}

	/** 
	 * Set the type.
	 * @param type The type to set
	 */
	public void setType(String type) {
		this.type = type;
	}

	/** 
	 * Returns the title.
	 * @return String
	 */
	public String getTitle() {
		return title;
	}

	/** 
	 * Set the title.
	 * @param title The title to set
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/** 
	 * Returns the aendTime.
	 * @return String
	 */
	public String getAendTime() {
		return aendTime;
	}

	/** 
	 * Set the aendTime.
	 * @param aendTime The aendTime to set
	 */
	public void setAendTime(String aendTime) {
		this.aendTime = aendTime;
	}

	/** 
	 * Returns the canping.
	 * @return String
	 */
	public String getCanping() {
		return canping;
	}

	/** 
	 * Set the canping.
	 * @param canping The canping to set
	 */
	public void setCanping(String canping) {
		this.canping = canping;
	}

	/** 
	 * Returns the context.
	 * @return String
	 */
	public String getContext() {
		return context;
	}

	/** 
	 * Set the context.
	 * @param context The context to set
	 */
	public void setContext(String context) {
		this.context = context;
	}

	/** 
	 * Returns the beiping.
	 * @return String
	 */
	public String[] getBeiping() {
		return beiping;
	}

	/** 
	 * Set the beiping.
	 * @param beiping The beiping to set
	 */
	public void setBeiping(String[] beiping) {
		this.beiping = beiping;
	}

	/** 
	 * Returns the allowAffix.
	 * @return Boolean
	 */
	public Boolean getAllowAffix() {
		return allowAffix;
	}

	/** 
	 * Set the allowAffix.
	 * @param allowAffix The allowAffix to set
	 */
	public void setAllowAffix(Boolean allowAffix) {
		this.allowAffix = allowAffix;
	}

	/** 
	 * Returns the endTime.
	 * @return String
	 */
	public String getEndTime() {
		return endTime;
	}

	/** 
	 * Set the endTime.
	 * @param endTime The endTime to set
	 */
	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String[] getOptions() {
		return options;
	}

	public void setOptions(String[] options) {
		this.options = options;
	}

	public int[] getEscores() {
		return escores;
	}

	public void setEscores(int[] escores) {
		this.escores = escores;
	}

	public int[] getTscores() {
		return tscores;
	}

	public void setTscores(int[] tscores) {
		this.tscores = tscores;
	}
}