/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.bysj.struts.action;

import java.io.IOException;
import java.io.UnsupportedEncodingException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.bysj.bean.MuserBean;
import com.bysj.common.StringUtil;
import com.bysj.dao.LoginDao;
import com.bysj.struts.form.LoginForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-07-2012
 * 
 * XDoclet definition:
 * @struts.action path="/loginAction" name="loginActionForm" input="/Login.jsp" parameter="action" scope="request" validate="true"
 * @struts.action-forward name="success" path="/index.jsp"
 * @struts.action-forward name="fail" path="/Login.jsp"
 */
public class LoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		LoginForm loginForm = (LoginForm) form;// TODO Auto-generated method stub

			String username = StringUtil.toGB2312(loginForm.getUsername());
			String pwd = loginForm.getPassword();
			
			MuserBean user = new MuserBean();
			user.setName(username);
			user.setPwd(pwd);
			
			LoginDao loginDao = new LoginDao();
			MuserBean newUser = loginDao.do_login(user);
			
			if(newUser.getId()!=0){
				HttpSession session = request.getSession();
				session.setAttribute("currUser", newUser);
				try {
					response.sendRedirect("vote.do?action=getVotes");
				} catch (IOException e) {
					e.printStackTrace();
				}
				return null;//mapping.findForward("success");
			}else 	
				return mapping.getInputForward();	
		}
}